# Docker Compose file for a Baikal server

version: "2"
services:
  baikal:
    image: ghcr.io/aalmenar/baikal:nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - config:/var/www/baikal/config
      - data:/var/www/baikal/Specific

volumes:
  config:
  data:
